version: "3"
services:
  candy-scrape:
    container_name: candy-scrape
    environment:
      - ENV=${ENV}
      - PACE=${PACE}
      - SECRET=${SECRET}
      - TOKEN=${TOKEN}
      - ID=${ID}
      - PUBLICID=${PUBLICID}
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/go/src/github.com/YusukeShimizu/Candy_Scrape
    working_dir: /go/src/github.com/YusukeShimizu/Candy_Scrape
    links:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
